# Generated by Django 6.0.1 on 2026-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
