# Generated by Django 6.0.1 on 2026-02-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_alamat_profile_nama_lengkap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nama_lengkap',
        ),
    ]
